### ISSUE TITLE
121 - Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by natebru** [ChrisLGardner/leetcode#16]
Weekly challenge

https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/

Best Time to buy and sell stock￼

**Comment by natebru** [comment]
@thomasrayner do you want to pick the next challenge? all look pretty good  :)

**Comment by thomasrayner** [comment]
@udubnate can do. Did everybody do this one? I lost count. Will select one tomorrow morning 😁
