### ISSUE TITLE
6. ZigZag Conversion

### ISSUE THREAD

**Issue by thomasrayner** [ChrisLGardner/leetcode#21]
https://leetcode.com/problems/zigzag-conversion/

Time for another one :)

**Comment by thomasrayner** [comment]
@udubnate @glennsarti no pressure at *all*, just bumping this in case you missed it :)

**Comment by natebru** [comment]
I am sadly going to pass this week and come back to it. Just too much stuff going on. I enjoyed walking through your solution and Chris as well though

**Comment by glennsarti** [comment]
Whoops I missed this :-(
 Looks like I'll have two challenges over the weekend

**Comment by thomasrayner** [comment]
No worries, @udubnate ! You know where to find us for the next one :D .
