### ISSUE TITLE
Do Challenge 26

### ISSUE THREAD

**Issue by glennsarti** [ChrisLGardner/leetcode#4]
https://leetcode.com/problems/remove-duplicates-from-sorted-array

**Comment by glennsarti** [comment]
Everyone has completed it

**Comment by thomasrayner** [comment]
I suppose someone should pick the next one? cc @glennsarti @ChrisLGardner

**Comment by ChrisLGardner** [comment]
> I suppose someone should pick the next one? cc @glennsarti @ChrisLGardner 

@thomasrayner already done, see the open issue.
